package com.pyroblinchik.catapi.domain.base.models


data class Breed(
    var id: String = "0",
    var weight: Weight? = null,
    var name: String? = null,
    var temperament: String? = null,
    var origin: String? = null,
    var countryCodes: String? = null,
    var countryCode: String? = null,
    var description: String? = null,
    var height: String? = null,
    var lifeSpan: String? = null,
    var indoor: Int? = null,
    var lap: Int? = null,
    var altNames: String? = null,
    var adaptability: Int? = null,
    var affectionLevel: Int? = null,
    var childFriendly: Int? = null,
    var dogFriendly: Int? = null,
    var energyLevel: Int? = null,
    var grooming: Int? = null,
    var healthIssues: Int? = null,
    var intelligence: Int? = null,
    var sheddingLevel: Int? = null,
    var socialNeeds: Int? = null,
    var strangerFriendly: Int? = null,
    var vocalisation: Int? = null,
    var experimental: Int? = null,
    var hairless: Int? = null,
    var natural: Int? = null,
    var rare: Int? = null,
    var rex: Int? = null,
    var suppressedTail: Int? = null,
    var shortLegs: Int? = null,
    var wikipediaUrl: String? = null,
    var hypoallergenic: Int? = null,
    var referenceImageId: Int? = null
)